language: objective-c
osx_image: xcode7.3

before_install:
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - fastlane travis

podfile: KakapoExample/Podfile

after_success:
- bash <(curl -s https://codecov.io/bash)
