language: objective-c

notifications:
  slack: devlucky:0AP12qjjfc2Zxc0s9yo1cQQm

env:
  global:
    - FASTLANE_LANE=ci_commit KKP_CODECOV=true

matrix:
  include:
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios83
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios93

script:
  - set -o pipefail
  - fastlane $FASTLANE_LANE configuration:Debug --env $FASTLANE_ENV

podfile: KakapoExample/Podfile

after_success:
  - bash <(curl -s https://codecov.io/bash)

