language: objective-c

notifications:
  slack: devlucky:0AP12qjjfc2Zxc0s9yo1cQQm

env:
  global:
    - FASTLANE_LANE=ci_commit

before_install:
  - gem update fastlane
  - gem update scan
  - gem install danger --no-ri --no-doc
  - gem install danger-swiftlint --no-ri --no-doc

matrix:
  include:
    - osx_image: xcode8
      env: FASTLANE_ENV=tvos
    - osx_image: xcode8
      env: FASTLANE_ENV=osx
    - osx_image: xcode8
      env: FASTLANE_ENV=ios93
    - osx_image: xcode8
      env: FASTLANE_ENV=ios10 KKP_CODECOV=true
      before_script:
        - danger
        - pod lib lint --quick
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'Kakapo'
        - sleep 5

script:
  - set -o pipefail
  - fastlane $FASTLANE_LANE configuration:Debug --env $FASTLANE_ENV

podfile: Podfile

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725

after_failure:
  - cat -n ~/Library/Logs/scan/*
