coverage:
  ignore:
    - Pods/.*
    - Tests/.*
    - Framework/.*
    - Source/NSURLRequest\+FixCopy\.swift
  
comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
